name: Lint iOS Code
on:
  workflow_dispatch:
#  pull_request:
#    branches: [ develop, main ]
jobs:
  test-iOS:
    permissions:
      contents: read
    name: Lint iOS Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
