name: Run E2E Tests for iOS
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
jobs:
  test-iOS:
    name: Test iOS App
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      # Use the bundler cache to speed-up build times
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ./LocationServices

      - name: Setup Config
        working-directory: ./LocationServices
        run: |
          base64 -d <<< ${{ secrets.CONFIG }} > Config.xcconfig
          base64 -d <<< ${{ secrets.TEST_CONFIG }} > ConfigTest.xcconfig

      - name: Run tests on iPhone
        working-directory: ./LocationServices
        run: bundle exec fastlane run_e2e_tests device:"iPhone 16 Pro Max (18.0)"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-iphone
          path: ${{ env.xcresult_path }}
          retention-days: 1
