name: Run E2E Tests for iOS
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
jobs:
  test-iOS:
    name: Test iOS App
    runs-on: macos-15-xlarge
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bundler
        working-directory: ./LocationServices
        run: |
          bundle config --local path ./vendor/bundle
          bundle config --local deployment true
          bundle install

      - name: Setup Config
        working-directory: ./LocationServices
        run: |
          base64 -d <<< ${{ secrets.CONFIG }} > Config.xcconfig
          base64 -d <<< ${{ secrets.TEST_CONFIG }} > ConfigTest.xcconfig

      - name: Run tests on iPhone
        working-directory: ./LocationServices
        env:
          XCRESULT_PATH: ${{ github.workspace }}/test_output/LocationServices.xcresult
        run: bundle exec fastlane run_e2e_tests device:"iPhone 16 Pro Max (18.0)"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-iphone
          path: ./LocationServices/test_output/
          retention-days: 1