name: Test IOS App
on:
  workflow_dispatch:
  pull_request:
    branches: [ develop, main ]
jobs:
  test-iOS:
    name: Test iOS
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2

      - name: Select xcode version
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "14.3"

      - name: Setup Bundler
        working-directory: ./LocationServices
        run: |
          bundle config --local path ./vendor/bundle
          bundle config --local deployment true
          bundle install

      - name: Setup Config Files
        working-directory: ./LocationServices
        run: |
          base64 -d <<< ${{ secrets.TEST_CONFIG }} > ConfigTest.xcconfig

      - name: Run tests
        working-directory: ./LocationServices
        run: bundle exec fastlane test

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: ${{ env.xcresult_path }}
          retention-days: 1
